USE todo;
 CREATE TABLE user(
     id BIGINT  AUTO_INCREMENT PRIMARY KEY,
     userName VARCHAR(50) NOT NULL,
     email VARCHAR(50) NOT NULL,
     create_at DATETIME DEFAULT CURRENT_TIMESTAMP,
     modified_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

)